site_name: UCT eResearch Documentation
site_url: https://uct-eresearch.github.io/mkdocs-poc/

use_directory_urls: true

theme:
  name: material
  logo: img/logo.png
  favicon: img/favicon.png
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.sections
    - navigation.prune
    - navigation.indexes
    - content.tabs.link
    - toc.integrate
    - navigation.path
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - toc.follow          # Highlight on scroll

  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - tables
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - toc:
      permalink: true      # Add anchor links
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      toc_depth: 3        # Maximum depth

plugins:
  - glightbox
  - search

extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - manage
      - reject

copyright: >
  Copyright &copy; 2025 University of Cape Town - <a href="#__consent">Change cookie settings</a>

nav:
  - High Performance Computing (HPC): 
      - BASIC INFORMATION: hpc/welcome.md
      - QUICK START: hpc/start/quick-start.md
      - SUBMITTING & MONITORING JOBS: hpc/jobs.md
      - SOFTWARE & ENVIRONMENTS: hpc/software.md
      - DATA & STORAGE: hpc/data.md
      - INTERACTIVE & PORTALS: hpc/portals.md
      - SYSTEMS & HARDWARE: hpc/systems.md
      - TROUBLESHOOTING & FAQ: hpc/help.md
      - PERFORMANCE & OPTIMISATION: hpc/perf.md
      - POLICIES & GOVERNANCE: hpc/policies.md
      - TRAINING & HOWTOs: hpc/training.md
  - Research Data Management (RDM): 
      - BASIC INFORMATION: rdm/index.md
      - DATA STORAGE: rdm/storage.md
      - DATA TRANSFER: rdm/transfer.md
  - Research Software Engineering (RSE):
      - RESOURCES: rse/resources.md
      - TRAINING: rse/training.md
  - Glossary of Terms: glossary.md