site_name: UCT eResearch Documentation
site_url: https://uct-eresearch.github.io/mkdocs-poc/
theme:
  name: material
  logo: img/logo.png
  favicon: img/favicon.png
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    - navigation.prune
    - navigation.indexes
    - content.tabs.link
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower


extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - manage
      - reject

copyright: >
  Copyright &copy; 2025 University of Cape Town - <a href="#__consent">Change cookie settings</a>

nav:
  - About UCT eResearch: index.md
  - High Performance Computing: 
    - hpc/index.md
    - Getting access: hpc/access.md
    - Logging in: hpc/login.md
  - Research Data Storage:
    - data/index.md
    - Data storage options: data/options.md
    - Getting access: data/access.md
